DROP DATABASE IF EXISTS test_db;

CREATE DATABASE test_db;

USE test_db;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  password VARCHAR(255),
  otp VARCHAR(255)
);

ALTER TABLE users
ADD role VARCHAR(255);


SELECT * FROM USERS;

CREATE TABLE tasks (
  task_id INT AUTO_INCREMENT PRIMARY KEY,
  task_name VARCHAR(255),
  task_desc VARCHAR(255),
  assigned_to VARCHAR(255),
  task_hours VARCHAR(255)
);

SELECT * FROM TASKS;